### ISSUE TITLE
Local resources

### ISSUE THREAD

**Issue by Default4152** [EileenRice/f1-3-c2p1-colmar-academy#6]
Great! I really like how you downloaded all of the images and stuck them in a folder. These local resources allow for faster page loading, as well as making your project more organized.

**Comment by EileenRice** [comment]
It certainly is good to have all media/folders with the project for those "just in case" moments.  I just wish Codecademy taught a bit more about local files, etc. It took a few minutes to figure out the "filing system."  Regardless, it was a learning experience.
